---
version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      - PORT=4000
      - BINDING=127.0.0.1
    ports:
      - "4000:4000"
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match should match what your application expects. In this case, the
      # compose file is in a sub-folder, so we will mount '..'. We'll then reference this
      # as the workspaceFolder in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/app:cached

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
      - "database:/opt/streamy/data"

volumes:
  database: